server:
  port: 8761

# http://localhost:8761 is the url where the registry is running line no.14
# THis is a registry, so do not self register eureka to eureka line no. 16
# This is a registry, so do not fetch the registry line no. 15


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}
    fetch-registry: false
    register-with-eureka: false